/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QuickLearnRouteImport } from './routes/quick-learn'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CopyRouteImport } from './routes/copy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as ApiPublicHooksNewsFetchRouteImport } from './routes/api/public/hooks/news-fetch'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickLearnRoute = QuickLearnRouteImport.update({
  id: '/quick-learn',
  path: '/quick-learn',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyRoute = CopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNewsFetchRoute = ApiPublicHooksNewsFetchRouteImport.update({
  id: '/api/public/hooks/news-fetch',
  path: '/api/public/hooks/news-fetch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/copy': typeof CopyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quick-learn': typeof QuickLearnRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/api/public/hooks/news-fetch': typeof ApiPublicHooksNewsFetchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/copy': typeof CopyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quick-learn': typeof QuickLearnRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/api/public/hooks/news-fetch': typeof ApiPublicHooksNewsFetchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/copy': typeof CopyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quick-learn': typeof QuickLearnRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/api/public/hooks/news-fetch': typeof ApiPublicHooksNewsFetchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/copy'
    | '/login'
    | '/notifications'
    | '/quick-learn'
    | '/search'
    | '/signup'
    | '/profile/$username'
    | '/projects/$id'
    | '/projects/new'
    | '/api/public/hooks/news-fetch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/copy'
    | '/login'
    | '/notifications'
    | '/quick-learn'
    | '/search'
    | '/signup'
    | '/profile/$username'
    | '/projects/$id'
    | '/projects/new'
    | '/api/public/hooks/news-fetch'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/copy'
    | '/login'
    | '/notifications'
    | '/quick-learn'
    | '/search'
    | '/signup'
    | '/profile/$username'
    | '/projects/$id'
    | '/projects/new'
    | '/api/public/hooks/news-fetch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CopyRoute: typeof CopyRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  QuickLearnRoute: typeof QuickLearnRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ApiPublicHooksNewsFetchRoute: typeof ApiPublicHooksNewsFetchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-learn': {
      id: '/quick-learn'
      path: '/quick-learn'
      fullPath: '/quick-learn'
      preLoaderRoute: typeof QuickLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy': {
      id: '/copy'
      path: '/copy'
      fullPath: '/copy'
      preLoaderRoute: typeof CopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/news-fetch': {
      id: '/api/public/hooks/news-fetch'
      path: '/api/public/hooks/news-fetch'
      fullPath: '/api/public/hooks/news-fetch'
      preLoaderRoute: typeof ApiPublicHooksNewsFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CopyRoute: CopyRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  QuickLearnRoute: QuickLearnRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ApiPublicHooksNewsFetchRoute: ApiPublicHooksNewsFetchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
